### ISSUE TITLE
动态查询的地图图片录制不下来

### ISSUE THREAD

**Issue by TianKongXiaSha** [metersphere/chrome-extensions#1]
用chrome插件录制的jmeter脚本只录制了非静态资源的请求，静态资源的请求没有录制下来。
有时候，图片等所谓的静态资源可能是需要从库里面查出来的，也需要做性能测试和压力测试，所以希望有不过滤静态资源的选项。

**Comment by q4speed** [comment]
@wangzhen-fit2cloud 增加了高级选项，可选择是否录制image，css，js等，等待测试。
